# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Custom Cuisine Catering
tagline: Custom Catering at Reasonable Prices
summary: Full-service McKinney-based catering serving the North Texas Metroplex
email: wilsonrsw@sbcglobal.net
description: >- # this means to ignore newlines until "baseurl:"
  Based in McKinney, Texas, Custom Cuisine Catering is a full-service caterer
  for corporate, private and special events. Let us take care of the cooking 
  and service so you can sit back and enjoy your event.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
#remote_theme: "mmistakes/minimal-mistakes"
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

repository: abettermap/custom-cuisine-site.github.io
facebook_username: "Custom-Cuisine-Catering-1578220195769725"

header_pages:
  - home.md
  - services.md
  - food.md
  - about.md

sass:
  sass_dir: assets
# defaults:
#   values:
#     nav: "foo"
#     sidebar:
#       nav: "foo"
#     header:
#       nav: "foo"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
